name: Android CI

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"
jobs:
  build:

    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit Test
        run: ./gradlew :app:testDebug
